version: '2'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    user: root
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    user: root
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_MESSAGE_MAX_BYTES=104857600
      - KAFKA_REPLICA_FETCH_MAX_BYTES=104857600
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
